spring.application.name=belajar-spring-config-properties
spring.application.version=1
spring.application.production=false

spring.profiles.active=local

spring.profile.default=Default

spring.application.database.username=eko
spring.application.database.password=rahasia
spring.application.database.database=belajar
spring.application.database.url=jdbc:contoh